// AUTO-GENERATED by scripts/build-sk-labels.mjs — DO NOT EDIT.
// Source: public/nrlp_3j.json (zirkularitaet.schluesselkompetenzen + Thema "Schlussarbeit").
// Regenerate with: npm run build:sk-labels (runs automatically on prebuild).

/** Short SK label keyed by numeric id (1..12). */
export const skShortByNr: Record<number, string> = {
  "1": "Quellen unterscheiden",
  "2": "Ziele setzen und anpassen",
  "3": "Innovation und Problemlösungen entwickeln",
  "4": "In Teams arbeiten",
  "5": "Werthaltungen reflektieren",
  "6": "Standpunkte begründen",
  "7": "Verständnis fördern",
  "8": "Lebensphasen planen",
  "9": "Nachhaltig handeln",
  "10": "Mit Wandel umgehen (Anpassung)",
  "11": "Mit Mehrdeutigkeiten umgehen",
  "12": "Partizipation"
}

/** Full Bildungsrat sentence keyed by short SK label. */
export const skFullName: Record<string, string> = {
  "Quellen unterscheiden": "Zwischen relevanten und irrelevanten Quellen und Inhalten unterscheiden",
  "Ziele setzen und anpassen": "Sich selbst Ziele setzen, die Zielsetzung überprüfen und sich adaptiv verhalten",
  "Innovation und Problemlösungen entwickeln": "Antizipative, unternehmerische und innovative Wege der Problemlösung erkennen, entwickeln und umsetzen",
  "In Teams arbeiten": "In unterschiedlichen Teams zielgerichtet und effizient arbeiten",
  "Werthaltungen reflektieren": "Die eigenen Werthaltungen und Überzeugungen erkennen, verstehen, kritisch reflektieren und weiterentwickeln",
  "Standpunkte begründen": "Ihre eigenen Standpunkte begründen und andere davon überzeugen",
  "Verständnis fördern": "Unterschiedliche Standpunkte nachvollziehen und das gegenseitige Verständnis fördern",
  "Lebensphasen planen": "Ihre Lebensphasen planen und mit Unwägbarkeiten umgehen",
  "Nachhaltig handeln": "Vernetzt und systemisch denken, um sozial, ökologisch und ökonomisch nachhaltig zu handeln",
  "Mit Wandel umgehen (Anpassung)": "Sich in einem sich ständig verändernden Umfeld zurechtfinden und sich an dieses anpassen",
  "Mit Mehrdeutigkeiten umgehen": "Mit Mehrdeutigkeiten umgehen",
  "Partizipation": "An gesellschaftlichen Prozessen partizipieren und Handlungsspielräume nutzen"
}
