<#
  import-nrlp-graph.ps1
  ----------------------
  Copies the self-contained nRLP network/Zirkularitaet graph app from the
  hko-deploy repo into bbw-hko as a static passthrough under public/nrlp/,
  WITHOUT the source material (Lehrmittel, PDFs, prompt-builder, python).

  It also:
    * copies the shared modal helper + the three nrlp-graph modal fragments
    * does NOT copy hko-deploy's bundled nrlp_*.json  (bbw-hko's own
      public/nrlp_{2j,3j,4j}.json are the fresher single source of truth)
    * patches the dataset paths in the copied app to the absolute
      /nrlp_{2j,3j,4j}.json so they resolve to bbw-hko's public root
    * stages the einheiten/situationen indexes under public/nrlp/ so the
      "units as nodes" overlay can fetch them at runtime

  Run from the bbw-hko repo root:
      pwsh ./scripts/import-nrlp-graph.ps1
  or point at a non-default hko-deploy checkout:
      pwsh ./scripts/import-nrlp-graph.ps1 -Source "D:\path\to\hko-deploy"

  Idempotent: re-running overwrites the vendored app files in place.
  It never deletes anything outside public/nrlp, public/shared, public/modals.
#>

param(
  [string]$Source = "..\hko-deploy",
  [string]$Dest   = "."
)

$ErrorActionPreference = "Stop"

$srcNrlp   = Join-Path $Source "public\nrlp"
$srcShared = Join-Path $Source "public\shared"
$srcModals = Join-Path $Source "public\modals"

$dstNrlp   = Join-Path $Dest "public\nrlp"
$dstShared = Join-Path $Dest "public\shared"
$dstModals = Join-Path $Dest "public\modals"

if (-not (Test-Path $srcNrlp)) {
  throw "Source app not found: $srcNrlp  (pass -Source <path-to-hko-deploy>)"
}

New-Item -ItemType Directory -Force -Path $dstNrlp, $dstShared, $dstModals | Out-Null

# --- 1) App shell (root files we want, NOT the *.json) -----------------------
foreach ($f in @("index.html", "app.js", "style.css", "favicon.png")) {
  $p = Join-Path $srcNrlp $f
  if (Test-Path $p) { Copy-Item $p (Join-Path $dstNrlp $f) -Force }
}

# --- 2) The ES module tree ---------------------------------------------------
$srcModules = Join-Path $srcNrlp "modules"
$dstModules = Join-Path $dstNrlp "modules"
if (Test-Path $dstModules) { Remove-Item $dstModules -Recurse -Force }
Copy-Item $srcModules $dstModules -Recurse -Force

# --- 3) Shared modal helper + nrlp-graph modal fragments ---------------------
foreach ($f in @("modals.css", "modals.js")) {
  $p = Join-Path $srcShared $f
  if (Test-Path $p) { Copy-Item $p (Join-Path $dstShared $f) -Force }
}
foreach ($f in @("nrlp-graph-optionen.html", "nrlp-graph-nutzung.html", "nrlp-graph-tabs.html")) {
  $p = Join-Path $srcModals $f
  if (Test-Path $p) { Copy-Item $p (Join-Path $dstModals $f) -Force }
}

# --- 4) Point the app at bbw-hko's own JSON (absolute /nrlp_*.json) -----------
#     hko-deploy uses "./nrlp_3j.json" (relative to /nrlp/). We rewrite to the
#     public root so there is ONE source of truth (bbw-hko/public/nrlp_*.json).
$indexHtml = Join-Path $dstNrlp "index.html"
(Get-Content $indexHtml -Raw) `
  -replace '"\./(nrlp_\dj\.json)"', '"/$1"' |
  Set-Content $indexHtml -Encoding UTF8

# Inject <base> so the app's relative assets (style.css, app.js, ./ext/*) resolve
# under /nrlp/ even when Vercel serves this directory index at the bare /nrlp
# path (no trailing slash) — where relative URLs would otherwise hit the site root.
(Get-Content $indexHtml -Raw) `
  -replace '(<meta charset="UTF-8"[^>]*>)', "`$1`n  <base href=""/nrlp/"" />" |
  Set-Content $indexHtml -Encoding UTF8

# Drop the Spirale + Sankey extra views (we keep only Chord). Removes the two
# view buttons and the now-unneeded d3-sankey CDN; the Chord view is enhanced
# with click-to-highlight in ext/visualizations.js (not copied by this import).
(Get-Content $indexHtml -Raw) `
  -replace '\s*<button class="view-btn" data-view="spirale">[^<]*</button>', '' `
  -replace '\s*<button class="view-btn" data-view="sankey">[^<]*</button>', '' `
  -replace '\s*<script src="https://unpkg\.com/d3-sankey[^"]*"></script>', '' |
  Set-Content $indexHtml -Encoding UTF8

$stateJs = Join-Path $dstModules "state.js"
(Get-Content $stateJs -Raw) `
  -replace "'\./(nrlp_\dj\.json)'", "'/`$1'" |
  Set-Content $stateJs -Encoding UTF8

$controllerJs = Join-Path $dstModules "app\controller.js"
(Get-Content $controllerJs -Raw) `
  -replace "'\./(nrlp_\dj\.json)'", "'/`$1'" `
  -replace "const EXTRA = \['spirale', 'chord', 'sankey'\];", "const EXTRA = ['chord'];" |
  Set-Content $controllerJs -Encoding UTF8

# --- 5) Stage the unit indexes for the "units as nodes" overlay --------------
#     These are regenerated by `npm run sync:situationen` /
#     `npm run build:einheiten-index`; see package.json hook note in the handoff.
#     Also consumed by the prompt-builder's interim Orientierungsbeispiel.
Copy-Item (Join-Path $Dest "src\data\einheiten.index.json")   (Join-Path $dstNrlp "einheiten.index.json")   -Force
Copy-Item (Join-Path $Dest "src\data\situationen.index.json") (Join-Path $dstNrlp "situationen.index.json") -Force

# --- 6) Prompt-Builder (sub-app under /nrlp/prompt-builder/) ------------------
#     Static ES-module app; reads the same nrlp_*.json. We copy only the app
#     files (NOT the *.md reference docs, NOT the bundled *.json).
$srcPB = Join-Path $srcNrlp "prompt-builder"
$dstPB = Join-Path $dstNrlp "prompt-builder"
if (Test-Path $srcPB) {
  New-Item -ItemType Directory -Force -Path $dstPB | Out-Null
  foreach ($f in @("index.html", "app.js", "prompts.js", "render.js", "state.js", "style.css", "favicon.png")) {
    $p = Join-Path $srcPB $f
    if (Test-Path $p) { Copy-Item $p (Join-Path $dstPB $f) -Force }
  }
  # Point the picker at bbw-hko's own JSON. Source uses "../nrlp_3j.json"
  # (relative to /nrlp/prompt-builder/). Rewrite to absolute /nrlp_*.json.
  $pbIndex = Join-Path $dstPB "index.html"
  (Get-Content $pbIndex -Raw) -replace '"\.\./(nrlp_\dj\.json)"', '"/$1"' | Set-Content $pbIndex -Encoding UTF8
  # Same <base> fix for the sub-app, scoped to its own directory.
  (Get-Content $pbIndex -Raw) `
    -replace '(<meta charset="UTF-8"[^>]*>)', "`$1`n  <base href=""/nrlp/prompt-builder/"" />" |
    Set-Content $pbIndex -Encoding UTF8
  $pbApp = Join-Path $dstPB "app.js"
  (Get-Content $pbApp -Raw) -replace "'\.\./(nrlp_\dj\.json)'", "'/`$1'" | Set-Content $pbApp -Encoding UTF8
  Write-Host "prompt-builder imported into $dstPB" -ForegroundColor Green
}

# --- 7) Repair mojibake -------------------------------------------------------
#     The hko-deploy sources are double-encoded UTF-8 (cp1252-misread): the
#     prompt-builder's render.js carries "Â·" for the middot and "â–¾"/"â–¸" for
#     the LB toggle arrows, plus box-drawing "â”€" in code comments. Copy-Item is
#     a byte copy, so it faithfully reproduces the corruption — we must actively
#     repair after copying (a plain re-encode can't fix already-double-encoded
#     bytes). scripts/fix-mojibake.py uses ftfy (mixed-corruption safe: leaves
#     clean UTF-8 like "ä" alone) and self-bootstraps ftfy if missing.
$fixScript = Join-Path $Dest "scripts\fix-mojibake.py"
if (Test-Path $fixScript) {
  Write-Host "Repairing mojibake in the imported files ..." -ForegroundColor Cyan
  & python $fixScript --write
}

Write-Host "nRLP graph + prompt-builder imported into $dstNrlp" -ForegroundColor Green
Write-Host "Next: apply the edits in docs/handoff-nrlp-graph.md and docs/handoff-nrlp-prompt-builder.md, then 'npm run build'." -ForegroundColor Yellow
